[tool.poetry]
name = "crypto-demo"
version = "0.1.0"
description = "A demo project for cryptographic operations"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
cryptography = "^39.0.1"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
