name: pqc_test_env
channels:
  - defaults
dependencies:
  - python=3.8
  - cryptography>=3.3.2  # Non-PQC
  - pycryptodome=3.14.1  # Non-PQC
  - pyca=1.1.0           # PQC
  - openssl=1.1.1        # Non-PQC
  - pip
  - pip:
      - pytest

